# action.yml
name: 'Run Effrit as a Github Action'
description: 'A simple action to run Effrit on a project. Either as a PR checker or, as a scanner tool.'
inputs:
  owner:  # id of input
    description: 'The owner of the repo'
    required: true
    default: ''
  pr_number:  # id of input
    description: 'The number of the PR'
    required: true
    default: ''
  repo:
    description: 'The name of the repository'
    required: true
    default: ''
  project_name:
    description: 'The name of the project'
    required: true
    default: ''
  parallel_files:
    description: 'The number of files to process in parallel.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --owner ${{ inputs.owner }}
    - --pr-number ${{ inputs.pr_number }}
    - --repo ${{ inputs.repo }}
    - --project-name ${{ inputs.project_name }}
    - --parallel-files ${{ inputs.parallel_files }}
branding:
  icon: "arrow-right-circle"
  color: purple
author: "Gergely Brautigam"
